# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'apovstyanoy@shakuro.com'
  config.password       = 'arifmetika'
  config.integrator_key = 'SHAK-e87e8fcf-09fe-4919-83d8-8941534be541'
  config.account_id     = '446141'
  config.endpoint       = 'https://demo.docusign.net/restapi'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

